#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK_DIR="$ROOT_DIR/requirements"
PYTHONS=(python3.10 python3.11 python3.12 python3.13)
PIP_VERSION="26.2.1"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/redposture-locks.XXXXXX")"

cleanup() {
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

mkdir -p "$LOCK_DIR"

freeze_lock() {
  local python_bin="$1"
  local lock_name="$2"
  shift 2
  local venv="$TMP_ROOT/$lock_name"
  "$python_bin" -m venv "$venv"
  "$venv/bin/python" -m pip install --upgrade "pip==$PIP_VERSION"
  "$venv/bin/python" -m pip install \
    -e "$ROOT_DIR$1" \
    "editables>=0.3" \
    "hatchling>=1.24.0" \
    "tox>=4.0.0" \
    "zstandard>=0.23.0" \
    "${@:2}"
  {
    echo "# Generated by scripts/update_ci_locks.sh; do not edit by hand."
    echo "# Exact versions are portable across macOS/Linux; artifact hashes are intentionally omitted."
    "$venv/bin/python" -m pip freeze --all --exclude-editable | LC_ALL=C sort -f
  } >"$LOCK_DIR/$lock_name.txt"
}

for python_bin in "${PYTHONS[@]}"; do
  if ! command -v "$python_bin" >/dev/null 2>&1; then
    echo "[!] missing required interpreter: $python_bin" >&2
    exit 2
  fi
  minor="${python_bin#python3.}"
  freeze_lock "$python_bin" "ci-py3${minor}" "[dev]"
done

freeze_lock python3.12 "release-py312" "" "build>=1.2.0" "pipx>=1.7.0"

echo "== CI lock files updated =="
