"""Shared ZooKeeper-protocol digest credential defaults."""

from __future__ import annotations

ZOOKEEPER_DIGEST_DEFAULT_CREDENTIALS: tuple[tuple[str, str], ...] = (
    ("admin", "admin"),
    ("admin", "changeme"),
    ("admin", "kafka"),
    ("admin", "password"),
    ("admin", "zookeeper"),
    ("broker", "broker"),
    ("broker", "brokerpass"),
    ("client", "client"),
    ("dev", "dev"),
    ("guest", "guest"),
    ("hadoop", "hadoop"),
    ("kafka", "changeme"),
    ("kafka", "kafka"),
    ("kafka", "password"),
    ("kafka", "zookeeper"),
    ("root", "admin"),
    ("root", "password"),
    ("root", "root"),
    ("root", "rootpass"),
    ("root", "zookeeper"),
    ("service", "password"),
    ("service", "service"),
    ("solr", "solr"),
    ("super", "super"),
    ("test", "test"),
    ("user", "password"),
    ("user", "user"),
    ("user1", "12345"),
    ("zk", "password"),
    ("zk", "zk"),
    ("zk", "zookeeper"),
    ("zookeeper", "admin"),
    ("zookeeper", "password"),
    ("zookeeper", "zookeeper"),
)

KEEPER_DIGEST_DEFAULT_CREDENTIALS: tuple[tuple[str, str], ...] = (
    ("admin", "admin"),
    ("admin", "changeme"),
    ("admin", "clickhouse"),
    ("admin", "keeper"),
    ("admin", "password"),
    ("clickhouse", "changeme"),
    ("clickhouse", "clickhouse"),
    ("clickhouse", "keeper"),
    ("clickhouse", "password"),
    ("default", ""),
    ("default", "changeme"),
    ("default", "clickhouse"),
    ("default", "default"),
    ("default", "password"),
    ("keeper", "changeme"),
    ("keeper", "clickhouse"),
    ("keeper", "keeper"),
    ("keeper", "password"),
    ("root", "clickhouse"),
    ("root", "keeper"),
    ("root", "password"),
    ("root", "root"),
    ("service", "password"),
    ("service", "service"),
    ("user", "password"),
    ("user", "user"),
)

__all__ = ["KEEPER_DIGEST_DEFAULT_CREDENTIALS", "ZOOKEEPER_DIGEST_DEFAULT_CREDENTIALS"]
